<a href="https://colab.research.google.com/github/weasel-codes/google-colab/blob/udemy-dl/DataPreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Impoting Libraries**
We Will be importing 3 libraries
* Numpy : Allows us to work with arrays
* MathPlotLib : Plot some charts. Will mainly use pyplot
* Panda : Import dataset and created matrices & vectors

In [32]:
import numpy as np
import matplotlib.pyplot as plot
import pandas as pd

# **Importing Datasets**
* Will use pandas library to import dataset. Dataset is imported inside a variable.
* Every ML problem has Features and dependent variables.
  * Here Features are Country, Age, Salary
  * Dependent VAriables : Purchased (usually last column of dataset)

In [33]:
dataset = pd.read_csv('Data.csv')
# Create Entites using indexes of csv
X = dataset.iloc[:, :-1].values #All the rows + all the columns except last
Y = dataset.iloc[:,-1] #Dependent vairables is last column

# **Taking Care of Missing Value**
* We dont want missing data in ML dataset as it may cause error in training dataset.
* Ignore data tupple if only 1% of such tupples are in dataset.
* Replace missing data with Avg of all the values in which data is missing. This is classically performed

Sykit learn is widely and very frequesntly used to work on datasets.
* Import imputter class.
* Create an object and first speciofy what type of values to replace with what and than use it on dataset.
* Than use this object to fill missing values of dataset.
  * fit() works only on numerical values and it is suggested to select all numerical columns at once since we are not sure which one of these columns might have missing values in huge datasets.
  * Make sure to exclude string columns
  * Call transform to it since we have linked funcationality.
  * transform returns updated matrix so make sure you save it.



In [34]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:]) #connects to our matrix of features
print(X)
X[:,1:] = imputer.transform(X[:,1:]) #Sign to go forward
print("Now updated >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ")
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Now updated >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# **Encoding Categorical Data**
* Trying to find relation btw features and outcome
* We need to replace coountry column with three columns : one hawt coding
* We will also do same for Purchased

What we are trying to do is change our dataset in such a way that only numerical data remains.
  * OneHotEncoding for several type of data
  * LabelEncoding for 0s and 1s

## Encoding Independent Variables
* Will use two classes to do it 
  * CloumnTransformerClass : from Compose model of sykit library
  * OneHotClass : from Preprocess model of same Sykit library



In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# 'encoder' specifies that encoding ios needed to be done using OneHotEncoder
# remainder specifies that only selected column needs to be encoded and remainder columns 
# needs to be added to appended to the result
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

# Now we need to attach this functionality to matrix
X = np.array(ct.fit_transform(X)) # To create a matrix out of result

X #100 : france, 010 : Germany, 001 : spain (alphabetical?)


array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

## Encoding Dependent Variables
* We will use labelEncoder class to encode into 0 and 1 for resultant data

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# **Split Dataset in Training and Test Set**
> Should we do feature scaling before or after division?

After is the answer. We will be applying feature scaling on both type of data. 

Test Set is going to be like any real life new data coming in to get result. But if we are doing FS earlier, some of these type of data might of into Training and our system might learn it specifically. 

But when some data set comes that is totally unrelated to our test or training set, that might not give correct result... False positive case for have we trained properly?

In [37]:
# To create 4 separate set : 2 for training set of dependent and independent vars and same 2 for testing set
# XTrain XTest YTrain YTest

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1) #80:20 :: Train:Test

print("Train set for X : \n", X_train)
print("\n\nTest set for X : \n", X_test)
print("\n\nTrain set for Y : \n", Y_train)
print("\n\nTest set for Y : \n", Y_test)

Train set for X : 
 [[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


Test set for X : 
 [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Train set for Y : 
 [0 1 0 0 1 1 0 1]


Test set for Y : 
 [0 1]


# **Feature Scaling**
Why : Some of ML models we try to avoid some features dominating over others.

Process : Standardisation and Normalisation

Normalisation : when normal dist.

Standardisation : works all the time.

Feature scaling on everything other than test set

No scaling done on France, GErmany, Spain : since they already have value btw -+3 and we might get error country coz of it.

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:]) #We want only age and salary i.e. avoid taking in country since we dont want random values for it
X_test[:,3:] = sc.transform(X_test[:,3:])

X_train
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830127, -0.9069571034860731],
       [1.0, 0.0, 0.0, -0.44973664397484425, 0.20564033932253029]],
      dtype=object)